### ISSUE TITLE
Comparison results in Table.1

### ISSUE THREAD

**Issue by cuiziteng** [onpix/LLNeRF#1]
Thanks for your nice work! It's a great work, I have a question is that in Table.1 there are comparison results with normal light scenes, but I download the dataset and it does not seem to have the normal-lit part, so where can I find the normal-light images? Thanks~

<img width="474" alt="image" src="https://github.com/onpix/LLNeRF/assets/55396225/786b35db-3e6c-4a48-aae0-1431ec0ceef3">

**Comment by onpix** [comment]
Thanks for your attention and reminder! Sorry that I forgot these normal-light scenes. I need some time to find the RAW files and process them, and I will upload them later. The dataset link and "News" part will be updated accordingly.

**Comment by onpix** [comment]
`normal-light-scenes.tar.gz` updated.
