### ISSUE TITLE
About code

### ISSUE THREAD

**Issue by XLR-man** [onpix/LLNeRF#11]
![image](https://github.com/onpix/LLNeRF/assets/73239630/8c4e41c4-4131-430c-b38d-d632c7f98e6d)
Is the code above correspond to the density network？

And if i want to remove pos_enc，
can i do this？
```
x = lifted_means
inputs = x
```

**Comment by XLR-man** [comment]
Do you have the pretrained models about some scenes in your datasets? So that we can get more details

**Comment by XLR-man** [comment]
@onpix

**Comment by onpix** [comment]
Sorry for this code, it is for debugging and should not be in the release version. I will revise it soon.
PSNR(output, GT) is not computed in the training code, I compute it using the rendered images and corresponding after training.

**Comment by XLR-man** [comment]
”I compute it using the rendered images and corresponding after training“  It only calculate for the scenes with normal light images？ Is that mean for the scenes without normal light images，we can't get the psnr？

**Comment by onpix** [comment]
Yes.
