### ISSUE TITLE
No such file or directory:'/llnerf-dataset/***/transforms.json'

### ISSUE THREAD

**Issue by usernameforu** [onpix/LLNeRF#13]
When I try to run "bash train.sh",I firstly got the FileNotFoundError:"No such file or directory:'/LLNeRF/llnerf-dataset/book/transforms.json'."Then I tried all the datasets, but none own the 'transforms.json'. Could you help solve this problem? Thanks so much!

**Comment by onpix** [comment]
Please check the subfolders of the dataset, this problem may be caused when the colmap folders are not found:https://github.com/onpix/LLNeRF/blob/4efa39cbebd3c0685972cfb2d86bb9c2d65603d0/internal/datasets.py#L592

**Comment by usernameforu** [comment]
Thank you very much for your response. I have successfully reproduced your code with my own dataset now. I have some questions about the output results and would like to ask which of the 120 images are the final results. Also, can I convert the results to mesh files or PLY files to view them in applications like MeshLab? Looking forward to your answer. Thank you!
