### ISSUE TITLE
Inquiry regarding dataset image resolutions

### ISSUE THREAD

**Issue by blue-531** [onpix/LLNeRF#14]
I want to express my gratitude for making the LLNeRF dataset available. However, I have encountered a query while working with the dataset. I observed that during the evaluation of scenes like still2, still3, and still4 in the paper, there appears to be a difference in resolution between normal light images and low light images. Could you kindly offer a comprehensive explanation of how the resolution disparity was managed during the preprocessing phase?

**Comment by onpix** [comment]
The original versions of still2, still3, and still4 were in 4K resolution. We downscaled them during training to reduce the training time. Regarding the issue you raised, I noticed the low-light images are 1156x868 in resolution, but the normal-light versions of these three scenes are slightly different at 1155x868. This might stem from a small bug of different resize parameters used for the low-light and normal-light images. However, this will not impact the computation of metrics. If you want images with aligned resolutions, you can simply resize the normal-light images to 1156x868 using the bilinear interpolation method.
