### ISSUE TITLE
About Code RAW

### ISSUE THREAD

**Issue by andre20000131** [onpix/LLNeRF#15]
you lose the function at internal/dataset.py -- 625col. if you choose the mode is RAW, you don't have self.image_paths in your code.

you should add:
      colmap_files = sorted(utils.listdir(colmap_image_dir))
      image_files = sorted(utils.listdir(image_dir))
      colmap_to_image = dict(zip(colmap_files, image_files))
      image_paths = [os.path.join(image_dir, colmap_to_image[f])
                     for f in image_names]
      self.image_paths = np.array(image_paths)

after 625 col.

**Comment by onpix** [comment]
Thanks for pointing it out. However, our proposed model does not support RAW images - you can run the original multinerf code.
