### ISSUE TITLE
About the red background in rendering results

### ISSUE THREAD

**Issue by usernameforu** [onpix/LLNeRF#17]
Hello, I found that when rendering using your dataset and the dataset I made myself, the final result will have a red blur. This layer of red looks good on your data set, but it shows a messy pink shade on my data set. I would like to ask if this red can be removed?

**Comment by onpix** [comment]
Hi, thanks for your interest! Sorry for the late reply as I have been too busy recently. Could you please provide some illustrations of this problem? I am not sure what you mean by "pink shade".

**Comment by usernameforu** [comment]
Thanks a lot! I have solved it.

**Comment by XLR-man** [comment]
> Thanks a lot! I have solved it.

Can i ask you how it solved?

**Comment by pegasus2004** [comment]
> > Thanks a lot! I have solved it.
> 
> Can i ask you how it solved?

hello, may I ask you something about Pycolmap？
