### ISSUE TITLE
Normal-Light Images in LLNeRF Dataset

### ISSUE THREAD

**Issue by RunyuChen** [onpix/LLNeRF#18]
Hi, Dr.Wang. I am currently conducting research on low-light enhancement and plan to use the LLNeRF dataset for testing. However, I noticed that the dataset you released only includes normal-light images for three scenes. I would like to inquire if there are normal-light images available for other scenes, and if so, how I can access them.
![image](https://github.com/user-attachments/assets/3a71adca-9862-4b45-b640-fc67f14be79d)

**Comment by onpix** [comment]
Thanks for your interest. Unfortunately, we only have these normal light scenes. Because other scenes are captured under real low light conditions, there are no GT images.
