### ISSUE TITLE
About train!

### ISSUE THREAD

**Issue by XLR-man** [onpix/LLNeRF#4]
Hi
My GPU is V100 with 32GB memory. And I have only one gpu. But I found with your default setting, the training speed is very slow. For example, with the default setting(batch_size=1024.......), it takes about half an hour to finish 100 steps, so if i want to finish 10w steps,i need twenty days!
My question is why the speed is so slow? Can I change the batch_size to speed up? Or other variants need to change?Can you give me some suggestions?

**Comment by onpix** [comment]
Can you please check how long it takes to train the multinerf using the default settings? If it also takes 20 days, there might be an issue with your environment or machine. As far as I remember, I need around 12 hours on V100S or 8 hours on A100 to train our model or multinerf.

**Comment by XLR-man** [comment]
I found the code isn't train with GPU though i distributed one gpu. 
When i change the batch_size from 1024 to 1, it can run fastly.
But both are not use gpu, they use cpu
![image](https://github.com/onpix/LLNeRF/assets/73239630/e2a5d9b4-da99-4aa5-9eb4-3b5382651b58)
![image](https://github.com/onpix/LLNeRF/assets/73239630/6852de23-7b9a-4721-b658-c95b2929bdcd)
Do you know what is the problem?

**Comment by XLR-man** [comment]
![image](https://github.com/onpix/LLNeRF/assets/73239630/04fc9d91-ba6a-4218-943a-937867dea3f6)
Maybe is environment. How can i fix it?

**Comment by XLR-man** [comment]
the problem above i have fixed.But there is another problem:
![image](https://github.com/onpix/LLNeRF/assets/73239630/f60d9a32-7828-4dd1-bd46-d8cbdb0e3ed5)

**Comment by onpix** [comment]
It also looks like an environment problem. You may need to check the dependeny of packages.
