### ISSUE TITLE
About train my own datasets

### ISSUE THREAD

**Issue by XLR-man** [onpix/LLNeRF#5]
Hi,
When I train my own datasets, and after render it, there will be mp4 and other png. However, the mp4 i got can't be open:
![image](https://github.com/onpix/LLNeRF/assets/73239630/85fa53d4-f3c5-44fc-b282-0aee5001b064)

So i found the png, but it got wrong scenes:
![rgb_enhanced_008](https://github.com/onpix/LLNeRF/assets/73239630/b8f56f11-3830-4a31-968d-67c75c393794)
While the original and normal scene is :
![image](https://github.com/onpix/LLNeRF/assets/73239630/4dd9e58b-58de-42f6-b388-330740d86bc1)

So what is the problem?

**Comment by onpix** [comment]
please check if your camera poses are correct.

**Comment by XLR-man** [comment]
I am sure that my datasets is right, because it come from other paper, and i have run it successfully.
For example, the other dataset file structure is:
![image](https://github.com/onpix/LLNeRF/assets/73239630/651048f0-44c2-43b0-9c31-361edcfdaa9c)
the file "colmap_sparse" and "low" is correspond to your "sparse" and "images" files, i just copy the  "colmap_sparse" and "low" to your "sparse" and "images" files.
So i thank it should be train successfully, but it got the wrong results above......

**Comment by XLR-man** [comment]
Or how can i verify own datasets's file structure is correspond to yours

**Comment by onpix** [comment]
Note that there should be a `poses_bounds.npy` file: https://github.com/Fyusion/LLFF/tree/master#using-your-own-poses-without-running-colmap

**Comment by XLR-man** [comment]
I have got the pose_bounds.npy by your link，and I trained the scene again。and I got the render result：
![image](https://github.com/onpix/LLNeRF/assets/73239630/4e71c216-aaae-4b28-b2f3-8ac9b83b9690)
it seems that more blurred and a little bit of distortion.

However,I still can't open the mp4, it still warn me the error above.Why it can't open the mp4?

**Comment by onpix** [comment]
Yeah, because of our GPU limitation, we just use small networks and relatively sparse views for training. You could try larger networks or more dense views for better performance.
I guess the mp4 problem is because of file encoding. Try running ffmpeg manually to get mp4.

**Comment by XLR-man** [comment]
Ok，i‘ve try ffmpeg.And it warn that the images's resolution need to be both even number(height and width should divisible by 2). And finally i can get the mp4.

https://github.com/onpix/LLNeRF/assets/73239630/c2722ce5-b9d6-499c-ae90-3a0f0a0e3be6

So i think the problem is  images's resolution
