### ISSUE TITLE
About data supervision

### ISSUE THREAD

**Issue by XLR-man** [onpix/LLNeRF#6]
Why is the enhancement process unsupervised in the paper, but a data supervision function: E [η(̃cr)− η(cr)] is added, which makes the enhanced color approach the color of the low-light image? How can this achieve enhancement?

**Comment by onpix** [comment]
The data loss is not used for enhancement, but for learning the correct geometry of the scene, as our enhancement is applied for color only.

**Comment by XLR-man** [comment]
![image](https://github.com/onpix/LLNeRF/assets/73239630/5213896c-e3e4-4f23-9f89-3b1c46523501)
It looks like data loss is optimizing the radiation field, right? That is to make sure that the low light scene renders successfully?

And does the loss function use the RawNeRF loss function? Can I understand that the tone mapping function is added so that the value in brighter areas is not too large and the value in darker areas is not too small, facilitating the learning process in low light scenes?

**Comment by onpix** [comment]
Yeah, that's correct.
