### ISSUE TITLE
About pycolmap

### ISSUE THREAD

**Issue by ywaison** [onpix/LLNeRF#7]
When I run scripts/train.sh I met a problem about pycolmap
 from pycolmap import SceneManager
ImportError: cannot import name 'SceneManager' from 'pycolmap' (/home/gtyssg/miniconda3/envs/jax/lib/python3.9/site-packages/pycolmap.cpython-39-x86_64-linux-gnu.so)

**Comment by ywaison** [comment]
And I delete the "from pycolmap import SceneManager" another problem occured
    class NeRFSceneManager(pycolmap.SceneManager):
AttributeError: module 'pycolmap' has no attribute 'SceneManager'

**Comment by HulkM** [comment]
How did you fix it?

**Comment by yazdinip** [comment]
how was this fixed?

**Comment by ywaison** [comment]
Delete pycolmap and download it again




git clone https://github.com/rmbrualla/pycolmap.git ./internal/pycolmap













-----原始邮件-----
发件人:"Pedram Yazdinia" ***@***.***>
发送时间:2024-03-09 07:10:38 (星期六)
收件人: onpix/LLNeRF ***@***.***>
抄送: ywaison ***@***.***>, "State change" ***@***.***>
主题: Re: [onpix/LLNeRF] About pycolmap (Issue #7)






how was this fixed?

**Comment by ywaison** [comment]
Delete pycolmap and download it again




git clone https://github.com/rmbrualla/pycolmap.git ./internal/pycolmap




-----原始邮件-----
发件人:"Pan lei" ***@***.***>
发送时间:2024-03-02 22:39:40 (星期六)
收件人: onpix/LLNeRF ***@***.***>
抄送: ywaison ***@***.***>, "State change" ***@***.***>
主题: Re: [onpix/LLNeRF] About pycolmap (Issue #7)






How did you fix it?

**Comment by pegasus2004** [comment]
I followed your instruction, but it still exists some problem, could you help me? When I run the train.sh, it shows that   File "/home/zhangmeng/keyan/LLNeRF/internal/pycolmap/pycolmap/scene_manager.py", line 131, in load_images
    self._load_images_bin(input_file)
  File "/home/zhangmeng/keyan/LLNeRF/internal/pycolmap/pycolmap/scene_manager.py", line 162, in _load_images_bin
    points_array.fromfile(f, 3 * num_points2D)
ValueError: bytes length not a multiple of item size.                   I dont know how to fix it, thanks! bro
