### ISSUE TITLE
About the camera pose ground truth

### ISSUE THREAD

**Issue by Haru2022** [onpix/LLNeRF#8]
Hello, could you please share any suggestions about how to get the ground truth of the camere pose when you collecting the dataset? Cuz i did not find any instruction in your paper. Do you use colmap to register the low-light images in your dataset?

**Comment by onpix** [comment]
Yeah, I use colmap. Please note that the camera poses from colmap are not GT and you may need to tune the colmap and image settings to get good colmap results, as SFM in low-light conditions remains a problem.

**Comment by Haru2022** [comment]
Thanks for you response. Do you enlight the raw low-light image first and then implement colmap for the camera pose estimation?

**Comment by onpix** [comment]
My solution is to export both RAW and jpeg outputs produced by the camera. The RAW output is not processed and will be processed by the simple ISP of rawpy to generate low-quality inputs for the NeRF. The jpegs - usually already processed by the camera, typically have minimal noise and is well-lit, which is used as input of colmap to get camera poses.

**Comment by Haru2022** [comment]
many thanks! I tried to collect my own dataset and found that the colmap result based on the output of D455 color camera is very unsatisfying. Maybe I should further fine-tune the colmap parameters for a good result according to your suggestions. Thanks again.

**Comment by Haru2022** [comment]
Hello, may I ask how do you generate the jpegs for estimating the camera poses in detail? Cuz I find that using the low-light images you provide cannot generate good poses in some scene (like still2, white chair) with few feature points.
You said that the jpegs is proceesed by the camera, does it means the jpegs are automatically processed by the camera without any post-processing using your own program? Or did you design some simple post-processing program to process the raw images to make them have minimal noise and be well-lit as you said before?
Looking forward to your response very much! Thanks!

**Comment by onpix** [comment]
For example, I use my mobile phone to capture images while turning RAW mode on, so it will produce:
1. RAW images, which will be processed by rawpy to generate low-quality training images
2. and JPGs for running colmap, which are already processed by the camera ISP of the phone, typically including denoise, auto white balance, and other enhancement methods. Thus the quality is relatively high and can be used for getting camera poses.

**Comment by Haru2022** [comment]
Got it. Thank you.
